# My paths
export PATH="$PATH:$HOME/bin"

# Bash Completion
[[ -r $(brew --prefix)/etc/bash_completion ]] && . $(brew --prefix)/etc/bash_completion

# Autojump
[[ -r $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# ASDF
[[ -r $HOME/.asdf/asdf.sh ]] && . $HOME/.asdf/asdf.sh
[[ -r $HOME/.asdf/completions/asdf.bash ]] && . $HOME/.asdf/completions/asdf.bash

# Prompt
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM=verbose

export PS1='\W\[\e[1;32m\]$(__git_ps1)\[\e[0m\] (ᴖᴥᴖ) ▶ '

# Aliases and functions
for i in ~/.dotfiles/{aliases,functions}/*.sh ; do . $i ; done

# Default external editor
export EDITOR="subl -n -w"

# Bash
export HISTCONTROL="ignoreboth:erasedups"
shopt -s histappend
shopt -s globstar autocd

# Colors
export CLICOLOR=1
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# Display raw (colored) characters on less
export LESS=RS

