# My paths
export PATH="./bin:$PATH:$HOME/bin"

# Bash Completion
[[ -r $(brew --prefix)/etc/bash_completion ]] && . $(brew --prefix)/etc/bash_completion

# Autojump
[[ -r $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# ASDF
[[ -r $HOME/.asdf/asdf.sh ]] && . $HOME/.asdf/asdf.sh
[[ -r $HOME/.asdf/completions/asdf.bash ]] && . $HOME/.asdf/completions/asdf.bash

# Simplify NodeJS install
export NODEJS_CHECK_SIGNATURES=no

# Strip down Erlang install
export KERL_CONFIGURE_OPTIONS="--without-javac --without-odbc --without-eldap --without-diameter --without-megaco --without-common_test --without-eunit"

# Prompt
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM=verbose

_asdf () { asdf current $1 | sed -e 's/ .*//'; }

_RESET=$( tput sgr0)
_GIT=$(   tput bold; tput setab  0; tput setaf  2)
_ELIXIR=$(tput bold; tput setab 57; tput setaf 15)
_ERLANG=$(tput bold; tput setab  1; tput setaf 15)
_NODEJS=$(tput bold; tput setab 22; tput setaf 15)

export PS1='\W \
\[$_ELIXIR\]$(_asdf elixir)\[$_RESET\] \
\[$_ERLANG\]$(_asdf erlang)\[$_RESET\] \
\[$_NODEJS\]$(_asdf nodejs)\[$_RESET\]\
\[$_GIT\]$(__git_ps1)\[$_RESET\] \
$ '

# Aliases and functions
for i in ~/.dotfiles/{aliases,functions}/*.sh ; do . $i ; done

# Default external editor
export EDITOR="subl -n -w"

# Bash
export HISTCONTROL="ignoreboth:erasedups"
shopt -s histappend
shopt -s globstar autocd

# Colors
export CLICOLOR=1
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# Display raw (colored) characters on less
export LESS=RS

# History for Elixir IEx
export ERL_AFLAGS="-kernel shell_history enabled"
