#!/usr/bin/env bash
set -eo pipefail # Bash safe mode

################################################################################
echo "Setup OS defaults..."
defaults write com.apple.dock autohide -bool true

################################################################################
echo "Setup brew's bash..."
BREW_BASH="/usr/local/bin/bash"
grep -Fxe "$BREW_BASH" /etc/shells || {
  sudo tee -a /etc/shells <<< "$BREW_BASH"
}
[[ $SHELL == $BREW_BASH ]] || chsh -s "$BREW_BASH"

################################################################################
echo "Sync sublime settings..."
mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Packages/User/"
cd "$HOME/Library/Application Support/Sublime Text 3/Packages/User/"
[[ $(ls -A) ]] || {
  ln -vs $HOME/Dropbox/Sync/Sublime/User/*.sublime-keymap .
  ln -vs $HOME/Dropbox/Sync/Sublime/User/SublimeLinter
  ln -vs $HOME/Dropbox/Sync/Sublime/User/*.sublime-settings .
}

################################################################################
echo "Link remaining sync'd files..."
cd
[[ (-e "bin" || -L "bin") ]] || ln -vs $HOME/Dropbox/Sync/bin
[[ (-e ".gitconfig-home" || -L ".gitconfig-home") ]] || ln -vs $HOME/Dropbox/Sync/.gitconfig-home
[[ (-e ".gitconfig-work" || -L ".gitconfig-work") ]] || ln -vs $HOME/Dropbox/Sync/.gitconfig-work
mkdir -p code
cd code
[[ (-e "home" || -L "home") ]] || ln -vs $HOME/Dropbox/Sync/code/home
[[ (-e "work" || -L "work") ]] || ln -vs $HOME/Dropbox/Sync/code/work
[[ (-e "oss" || -L "oss") ]] || ln -vs $HOME/Dropbox/Sync/code/oss

################################################################################
echo "Install asdf..."
[[ -e ~/.asdf ]] || {
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf
  git checkout "$(git describe --abbrev=0 --tags)"
}

cd
